const world2RuntimeBase = "/assets/gvo/stations/world-2/pulse-invisible/runtime";
const liaBase = "/assets/gvo/shared/lia/current-used/portada-intro";

export const world2RuntimeAssets = {
  background: `${world2RuntimeBase}/background/world2_background_base_mobile_v01.webp`,
  ambientHaze: `${world2RuntimeBase}/atmosphere/world2_ambient_lavender_haze_v01.png`,
  foregroundSilhouette: `${world2RuntimeBase}/atmosphere/world2_foreground_botanical_silhouette_v01.png`,
  plant: `${world2RuntimeBase}/plant/world2_main_living_plant_v01.png`,
  plantStageAnchor: `${world2RuntimeBase}/plant/world2_plant_stage_anchor_v01.png`,
  plantAura: `${world2RuntimeBase}/plant/world2_living_plant_aura_v01.png`,
  rawWaveform: `${world2RuntimeBase}/signal/world2_raw_bioelectric_waveform_v01.png`,
  signalOriginContact: `${world2RuntimeBase}/signal/world2_signal_origin_contact_v01.png`,
  signalThreads: `${world2RuntimeBase}/signal/world2_bioelectric_signal_threads_v01.png`,
  pulseCore: `${world2RuntimeBase}/signal/world2_pulse_core_node_v01.png`,
  pulseRing: `${world2RuntimeBase}/signal/world2_pulse_expansion_ring_v01.png`,
  captureContact: `${world2RuntimeBase}/route/world2_signal_capture_contact_v01.png`,
  conditioningField: `${world2RuntimeBase}/route/world2_signal_conditioning_field_v01.png`,
  mappingConstellation: `${world2RuntimeBase}/route/world2_signal_mapping_constellation_v01.png`,
  mediatedResult: `${world2RuntimeBase}/route/world2_mediated_result_bloom_v01.png`,
  readyPath: `${world2RuntimeBase}/route/world2_ready_continue_signal_path_v01.png`,
  routeBase: `${world2RuntimeBase}/route/world2_mediation_route_base_v01.png`,
  routeActive: `${world2RuntimeBase}/route/world2_mediation_route_active_segment_v01.png`,
  dialogueBackplate: `${world2RuntimeBase}/dialogue/world2_dialogue_panel_backplate_v01.png`,
  dialogueCard: `${world2RuntimeBase}/dialogue/world2_dialogue_card_mobile_safe_v01.png`,
  dialogueGlow: `${world2RuntimeBase}/dialogue/world2_dialogue_panel_reveal_glow_v01.png`,
  dialogueTitleGlow: `${world2RuntimeBase}/dialogue/world2_dialogue_title_focus_glow_v01.png`,
  dialogueTail: `${world2RuntimeBase}/dialogue/world2_dialogue_lia_connector_tail_v01.png`,
  ctaButton: `${world2RuntimeBase}/navigation/world2_cta_organic_pulse_button_v01.png`,
  liaHalo: `${world2RuntimeBase}/lia-fx/world2_lia_presence_halo_v01.png`,
  liaDialogueGlow: `${world2RuntimeBase}/lia-fx/world2_lia_dialogue_focus_glow_v01.png`,
  liaGestureSpark: `${world2RuntimeBase}/lia-fx/world2_lia_gesture_signal_spark_v01.png`,
  liaWisps: `${world2RuntimeBase}/lia-fx/world2_lia_signal_attention_wisps_v01.png`,
  liaSparkleTrail: `${world2RuntimeBase}/lia-fx/world2_lia_transition_sparkle_trail_v01.png`,
  layerGlyphAtlas: `${world2RuntimeBase}/navigation/world2_layer_icon_glyphs_atlas_v01.png`,
  layerNavTokenBase: `${world2RuntimeBase}/navigation/world2_layer_nav_token_base_v01.png`,
  layerNavTokenActive: `${world2RuntimeBase}/navigation/world2_layer_nav_token_active_v01.png`,
  layerNavConnectorInactive: `${world2RuntimeBase}/navigation/world2_layer_nav_connector_inactive_v01.png`,
  layerNavFrame: `${world2RuntimeBase}/navigation/world2_layer_nav_frame_v01.png`,
  layerActiveGlow: `${world2RuntimeBase}/navigation/world2_layer_nav_active_slot_glow_v01.png`,
  layerLockGlyph: `${world2RuntimeBase}/navigation/world2_layer_status_lock_glyph_v01.png`,
  layerCompleteGlyph: `${world2RuntimeBase}/navigation/world2_layer_status_complete_glyph_v01.png`,
  layerConnector: `${world2RuntimeBase}/navigation/world2_layer_nav_connector_active_v01.png`,
  microFrame: `${world2RuntimeBase}/micro-scenes/world2_micro_scene_bubble_frame_v01.png`,
  microConnector: `${world2RuntimeBase}/micro-scenes/world2_micro_scene_bubble_connector_v01.png`,
  microFocusGlow: `${world2RuntimeBase}/micro-scenes/world2_micro_scene_bubble_focus_glow_v01.png`,
  microBase: `${world2RuntimeBase}/micro-scenes/world2_micro_scene_holographic_base_v01.png`,
  microCaptureReticle: `${world2RuntimeBase}/micro-scenes/world2_micro_scene_capture_reticle_v01.png`,
  liaIdle: `${liaBase}/lia_pose_idle_v1.png`,
  liaGreeting: `${liaBase}/lia_pose_greeting_v1.png`,
  liaExplainCalm: `${liaBase}/lia_pose_explain_calm_v1.png`,
  liaActivate: `${liaBase}/lia_pose_activate_portal_1_v1.png`,
  liaPoint: `${liaBase}/lia_pose_point_portal_1_v1.png`,
} as const;

export const world2InitialRuntimeAssetSources = [
  world2RuntimeAssets.background,
  world2RuntimeAssets.plant,
  world2RuntimeAssets.plantStageAnchor,
  world2RuntimeAssets.liaIdle,
  world2RuntimeAssets.dialogueCard,
  world2RuntimeAssets.layerNavTokenBase,
  world2RuntimeAssets.layerGlyphAtlas,
] as const;
