/** CTA and title: HUMAN_APPROVED / FINAL_COPY, LIA-M4-01 section 5. */
export const liaPreviewCopy = {
  status: "FINAL_COPY",
  entry: "Conversar con Lía",
  badge: "Fragmentos del recorrido",
  title: "Conversar con Lía",
  introduction:
    "Revisitemos el jardín. Puedo compartir fragmentos del recorrido y mostrarte sus fuentes.",
  chapter: "EL RECORRIDO CONTINÚA",
  reading: "Cuaderno de conversación",
  presence: "Una pregunta abre otro camino.",
  greeting: "Te escucho",
  listening: "Preparando tu pregunta",
  explaining: "Volvamos a lo que recorriste",
  showingSources: "Las palabras y sus fuentes",
  farewell: "Volvemos al Mirador",
  scope:
    "Esta conversación usa extractos del recorrido. Si no encuentro información suficiente, te lo diré.",
  empty: "¿Qué te gustaría recordar del recorrido?",
  suggestion: "¿Las plantas hacen música por sí solas?",
  prompt: "Tu pregunta",
  placeholder: "Escribe una pregunta sobre el recorrido…",
  send: "Enviar pregunta",
  clear: "Limpiar conversación",
  back: "Volver al Mirador",
  loading: "Buscando en el recorrido…",
  supported: "Encontré estos fragmentos",
  abstain: "No encontré evidencia suficiente",
  refused: "Esta solicitud está fuera de mi alcance",
  unavailable:
    "Lía no está disponible en este momento. Puedes intentarlo de nuevo o volver al Mirador.",
  sources: "Ver fuentes",
  you: "Tú",
  lia: "Lía",
  cleared: "Conversación borrada.",
  counter: "caracteres",
  limit: "Puedes escribir hasta 2000 caracteres.",
  session: "La conversación se borra al salir de esta pantalla.",
} as const;
