import type { Station4NodeId } from "./station4Content";

/**
 * Every coordinate in this module is local to the visible alpha bounding box
 * of the approved node raster. Values are ratios in the inclusive 0..1 range;
 * they are deliberately independent from viewport and artboard offsets.
 */
export type World4NormalizedPoint = readonly [x: number, y: number];

type World4NodeFxPrimitiveBase = {
  id: string;
  role: string;
  delayMs: number;
  durationMs: number;
  motion: string;
  reducedFallback: "hidden" | "opacity" | "static-highlight";
  cycles?: number;
  fill?: string;
  opacity?: number;
  stroke?: string;
  strokeWidth?: number;
};

export type World4NodeFxPrimitive =
  | (World4NodeFxPrimitiveBase & {
      kind: "circle";
      center: World4NormalizedPoint;
      radius: number;
    })
  | (World4NodeFxPrimitiveBase & {
      kind: "rect";
      origin: World4NormalizedPoint;
      size: World4NormalizedPoint;
      radius?: number;
    })
  | (World4NodeFxPrimitiveBase & {
      kind: "line";
      from: World4NormalizedPoint;
      to: World4NormalizedPoint;
    })
  | (World4NodeFxPrimitiveBase & {
      kind: "polyline";
      points: readonly World4NormalizedPoint[];
      closed?: boolean;
    })
  | (World4NodeFxPrimitiveBase & {
      kind: "arc";
      from: World4NormalizedPoint;
      control: World4NormalizedPoint;
      to: World4NormalizedPoint;
    });

export type World4NodeFxConfig = {
  nodeId: Station4NodeId;
  durationMs: number;
  coordinateSpace: "alpha_bbox_normalized";
  rootMotion: string;
  rootMotionAmplitude: number;
  reducedFallback: "static-highlight";
  primitives: readonly World4NodeFxPrimitive[];
};

const cyan = "#b8ddff";
const ivory = "#fff4da";
const lavender = "#c8b7f6";
const champagne = "#f2c784";
const ledRed = "#d96572";

export const WORLD4_NODE_FX_CONFIG = {
  planta: {
    nodeId: "planta",
    durationMs: 760,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "single-contained-sway",
    rootMotionAmplitude: 1.2,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "stem-rise",
        role: "living-origin-stem-highlight",
        kind: "line",
        from: [0.51, 0.88],
        to: [0.5, 0.2],
        delayMs: 0,
        durationMs: 720,
        motion: "rise-once",
        reducedFallback: "static-highlight",
        stroke: cyan,
        strokeWidth: 0.018,
        opacity: 0.72,
      },
      {
        id: "left-leaf",
        role: "leaf-differential-response",
        kind: "polyline",
        points: [
          [0.49, 0.56],
          [0.31, 0.48],
          [0.22, 0.37],
        ],
        delayMs: 90,
        durationMs: 650,
        motion: "expand-one-pixel-equivalent",
        reducedFallback: "static-highlight",
        stroke: lavender,
        strokeWidth: 0.014,
        opacity: 0.62,
      },
      {
        id: "right-leaf",
        role: "leaf-differential-response",
        kind: "polyline",
        points: [
          [0.51, 0.5],
          [0.68, 0.4],
          [0.78, 0.29],
        ],
        delayMs: 130,
        durationMs: 650,
        motion: "expand-two-pixel-equivalent",
        reducedFallback: "static-highlight",
        stroke: lavender,
        strokeWidth: 0.014,
        opacity: 0.62,
      },
      {
        id: "left-bud",
        role: "bud-contained-pulse",
        kind: "circle",
        center: [0.25, 0.34],
        radius: 0.045,
        delayMs: 180,
        durationMs: 520,
        motion: "scale-1-1.04-1",
        reducedFallback: "static-highlight",
        fill: ivory,
        opacity: 0.64,
      },
      {
        id: "right-bud",
        role: "bud-contained-pulse",
        kind: "circle",
        center: [0.79, 0.25],
        radius: 0.04,
        delayMs: 230,
        durationMs: 520,
        motion: "scale-1-1.04-1",
        reducedFallback: "static-highlight",
        fill: ivory,
        opacity: 0.64,
      },
    ],
  },
  bionosificador: {
    nodeId: "bionosificador",
    durationMs: 840,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "contact-left",
        role: "sensor-contact-left",
        kind: "circle",
        center: [0.21, 0.53],
        radius: 0.055,
        delayMs: 0,
        durationMs: 360,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.72,
      },
      {
        id: "contact-right",
        role: "sensor-contact-right",
        kind: "circle",
        center: [0.79, 0.53],
        radius: 0.055,
        delayMs: 80,
        durationMs: 360,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.72,
      },
      {
        id: "groove-left",
        role: "signal-groove-to-center",
        kind: "line",
        from: [0.24, 0.53],
        to: [0.47, 0.53],
        delayMs: 150,
        durationMs: 430,
        motion: "draw-to-center",
        reducedFallback: "opacity",
        stroke: lavender,
        strokeWidth: 0.018,
        opacity: 0.68,
      },
      {
        id: "groove-right",
        role: "signal-groove-to-center",
        kind: "line",
        from: [0.76, 0.53],
        to: [0.53, 0.53],
        delayMs: 190,
        durationMs: 430,
        motion: "draw-to-center",
        reducedFallback: "opacity",
        stroke: lavender,
        strokeWidth: 0.018,
        opacity: 0.68,
      },
      {
        id: "central-chamber",
        role: "conditioning-chamber",
        kind: "circle",
        center: [0.5, 0.53],
        radius: 0.09,
        delayMs: 360,
        durationMs: 430,
        motion: "scale-1-1.04-1",
        reducedFallback: "static-highlight",
        fill: ivory,
        stroke: champagne,
        strokeWidth: 0.012,
        opacity: 0.58,
      },
    ],
  },
  esp32: {
    nodeId: "esp32",
    durationMs: 760,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "shield-glint",
        role: "processor-shield-glint",
        kind: "line",
        from: [0.27, 0.75],
        to: [0.76, 0.23],
        delayMs: 0,
        durationMs: 460,
        motion: "diagonal-glint-once",
        reducedFallback: "static-highlight",
        stroke: ivory,
        strokeWidth: 0.022,
        opacity: 0.7,
      },
      {
        id: "status-led",
        role: "status-led-exactly-two-blinks",
        kind: "circle",
        center: [0.78, 0.72],
        radius: 0.035,
        delayMs: 80,
        durationMs: 600,
        motion: "blink",
        reducedFallback: "static-highlight",
        cycles: 2,
        fill: ledRed,
        opacity: 0.84,
      },
      {
        id: "data-point-a",
        role: "data-convergence",
        kind: "circle",
        center: [0.19, 0.33],
        radius: 0.022,
        delayMs: 120,
        durationMs: 480,
        motion: "converge-to-shield",
        reducedFallback: "opacity",
        fill: cyan,
        opacity: 0.74,
      },
      {
        id: "data-point-b",
        role: "data-convergence",
        kind: "circle",
        center: [0.17, 0.52],
        radius: 0.022,
        delayMs: 170,
        durationMs: 480,
        motion: "converge-to-shield",
        reducedFallback: "opacity",
        fill: lavender,
        opacity: 0.74,
      },
      {
        id: "data-point-c",
        role: "data-convergence",
        kind: "circle",
        center: [0.25, 0.72],
        radius: 0.022,
        delayMs: 220,
        durationMs: 480,
        motion: "converge-to-shield",
        reducedFallback: "opacity",
        fill: cyan,
        opacity: 0.74,
      },
    ],
  },
  midi: {
    nodeId: "midi",
    durationMs: 820,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "din-port",
        role: "midi-din-port",
        kind: "circle",
        center: [0.22, 0.5],
        radius: 0.075,
        delayMs: 0,
        durationMs: 420,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.64,
      },
      ...Array.from({ length: 6 }, (_, index) => ({
        id: `event-cell-${index + 1}`,
        role: "midi-event-cell",
        kind: "rect" as const,
        origin: [
          0.45 + (index % 3) * 0.13,
          0.34 + Math.floor(index / 3) * 0.23,
        ] as const,
        size: [0.085, 0.13] as const,
        radius: 0.012,
        delayMs: 120 + index * 70,
        durationMs: 250,
        motion: "sequential-cell-illumination",
        reducedFallback: "static-highlight" as const,
        fill: index === 5 ? champagne : lavender,
        opacity: 0.7,
      })),
      {
        id: "bridge-seam",
        role: "midi-bridge-seam",
        kind: "line",
        from: [0.32, 0.5],
        to: [0.43, 0.5],
        delayMs: 430,
        durationMs: 280,
        motion: "reveal-once",
        reducedFallback: "opacity",
        stroke: ivory,
        strokeWidth: 0.014,
        opacity: 0.62,
      },
    ],
  },
  wifi_udp: {
    nodeId: "wifi_udp",
    durationMs: 860,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      ...Array.from({ length: 3 }, (_, index) => ({
        id: `packet-${index + 1}`,
        role: "local-network-packet-cell",
        kind: "rect" as const,
        origin: [0.18 + index * 0.15, 0.66 - index * 0.09] as const,
        size: [0.075, 0.075] as const,
        radius: 0.01,
        delayMs: index * 85,
        durationMs: 300,
        motion: "packet-sequence-once",
        reducedFallback: "static-highlight" as const,
        fill: index === 2 ? ivory : cyan,
        opacity: 0.72,
      })),
      {
        id: "network-core",
        role: "local-network-core",
        kind: "circle",
        center: [0.53, 0.52],
        radius: 0.06,
        delayMs: 240,
        durationMs: 360,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: lavender,
        opacity: 0.68,
      },
      ...Array.from({ length: 3 }, (_, index) => ({
        id: `network-arc-${index + 1}`,
        role: "local-network-arc",
        kind: "arc" as const,
        from: [0.53 - (index + 1) * 0.06, 0.52] as const,
        control: [0.53, 0.34 - index * 0.08] as const,
        to: [0.53 + (index + 1) * 0.06, 0.52] as const,
        delayMs: 330 + index * 85,
        durationMs: 380,
        motion: "propagate-once",
        reducedFallback: "static-highlight" as const,
        stroke: index === 2 ? lavender : cyan,
        strokeWidth: 0.012,
        opacity: 0.64 - index * 0.08,
      })),
    ],
  },
  router: {
    nodeId: "router",
    durationMs: 820,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "wan-port",
        role: "router-wan-port",
        kind: "rect",
        origin: [0.26, 0.61],
        size: [0.12, 0.12],
        radius: 0.018,
        delayMs: 0,
        durationMs: 340,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: champagne,
        opacity: 0.72,
      },
      {
        id: "lan-port-1",
        role: "router-lan-port",
        kind: "rect",
        origin: [0.45, 0.61],
        size: [0.11, 0.12],
        radius: 0.018,
        delayMs: 90,
        durationMs: 340,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.68,
      },
      {
        id: "lan-port-2",
        role: "router-lan-port",
        kind: "rect",
        origin: [0.62, 0.61],
        size: [0.11, 0.12],
        radius: 0.018,
        delayMs: 180,
        durationMs: 340,
        motion: "pulse-once",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.68,
      },
      {
        id: "status-seam",
        role: "router-status-seam",
        kind: "line",
        from: [0.23, 0.52],
        to: [0.77, 0.52],
        delayMs: 240,
        durationMs: 430,
        motion: "sweep-once",
        reducedFallback: "opacity",
        stroke: lavender,
        strokeWidth: 0.014,
        opacity: 0.64,
      },
      {
        id: "antenna-fin-left",
        role: "router-antenna-fin-edge",
        kind: "line",
        from: [0.26, 0.42],
        to: [0.17, 0.13],
        delayMs: 330,
        durationMs: 390,
        motion: "edge-shimmer-once",
        reducedFallback: "static-highlight",
        stroke: ivory,
        strokeWidth: 0.012,
        opacity: 0.58,
      },
      {
        id: "antenna-fin-right",
        role: "router-antenna-fin-edge",
        kind: "line",
        from: [0.74, 0.42],
        to: [0.83, 0.13],
        delayMs: 400,
        durationMs: 390,
        motion: "edge-shimmer-once",
        reducedFallback: "static-highlight",
        stroke: ivory,
        strokeWidth: 0.012,
        opacity: 0.58,
      },
    ],
  },
  sistema_central: {
    nodeId: "sistema_central",
    durationMs: 880,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "main-display",
        role: "central-system-display",
        kind: "rect",
        origin: [0.2, 0.2],
        size: [0.6, 0.34],
        radius: 0.02,
        delayMs: 0,
        durationMs: 360,
        motion: "opacity-0.65-to-1",
        reducedFallback: "static-highlight",
        fill: cyan,
        opacity: 0.24,
      },
      {
        id: "scan-band",
        role: "central-system-scan-band",
        kind: "rect",
        origin: [0.22, 0.24],
        size: [0.56, 0.045],
        radius: 0.01,
        delayMs: 120,
        durationMs: 520,
        motion: "scan-once",
        reducedFallback: "hidden",
        fill: ivory,
        opacity: 0.38,
      },
      {
        id: "status-strip",
        role: "central-system-status-strip",
        kind: "line",
        from: [0.22, 0.58],
        to: [0.78, 0.58],
        delayMs: 260,
        durationMs: 360,
        motion: "reveal-once",
        reducedFallback: "static-highlight",
        stroke: lavender,
        strokeWidth: 0.016,
        opacity: 0.66,
      },
      ...Array.from({ length: 3 }, (_, index) => ({
        id: `lower-indicator-${index + 1}`,
        role: "central-system-lower-indicator",
        kind: "circle" as const,
        center: [0.36 + index * 0.14, 0.72] as const,
        radius: 0.035,
        delayMs: 360 + index * 75,
        durationMs: 280,
        motion: "sequential-indicator",
        reducedFallback: "static-highlight" as const,
        fill: index === 2 ? champagne : cyan,
        opacity: 0.68,
      })),
      {
        id: "front-inset",
        role: "central-system-front-inset",
        kind: "rect",
        origin: [0.27, 0.64],
        size: [0.46, 0.18],
        radius: 0.025,
        delayMs: 520,
        durationMs: 300,
        motion: "highlight-once",
        reducedFallback: "static-highlight",
        stroke: ivory,
        strokeWidth: 0.012,
        opacity: 0.48,
      },
    ],
  },
  sonido: {
    nodeId: "sonido",
    durationMs: 920,
    coordinateSpace: "alpha_bbox_normalized",
    rootMotion: "none",
    rootMotionAmplitude: 0,
    reducedFallback: "static-highlight",
    primitives: [
      {
        id: "diaphragm",
        role: "sound-diaphragm",
        kind: "circle",
        center: [0.5, 0.47],
        radius: 0.23,
        delayMs: 0,
        durationMs: 720,
        motion: "scale-1-1.035-0.99-1",
        reducedFallback: "static-highlight",
        cycles: 2,
        fill: lavender,
        opacity: 0.18,
        stroke: cyan,
        strokeWidth: 0.018,
      },
      {
        id: "inner-ring",
        role: "sound-inner-ring",
        kind: "circle",
        center: [0.5, 0.47],
        radius: 0.14,
        delayMs: 110,
        durationMs: 620,
        motion: "brightness-once",
        reducedFallback: "static-highlight",
        stroke: ivory,
        strokeWidth: 0.016,
        opacity: 0.66,
      },
      {
        id: "vent-left",
        role: "sound-vent-symmetric-response",
        kind: "line",
        from: [0.19, 0.68],
        to: [0.34, 0.62],
        delayMs: 250,
        durationMs: 420,
        motion: "symmetric-response-once",
        reducedFallback: "static-highlight",
        stroke: cyan,
        strokeWidth: 0.016,
        opacity: 0.58,
      },
      {
        id: "vent-right",
        role: "sound-vent-symmetric-response",
        kind: "line",
        from: [0.81, 0.68],
        to: [0.66, 0.62],
        delayMs: 250,
        durationMs: 420,
        motion: "symmetric-response-once",
        reducedFallback: "static-highlight",
        stroke: cyan,
        strokeWidth: 0.016,
        opacity: 0.58,
      },
      {
        id: "status-seam",
        role: "sound-status-seam",
        kind: "line",
        from: [0.28, 0.82],
        to: [0.72, 0.82],
        delayMs: 500,
        durationMs: 340,
        motion: "reveal-once",
        reducedFallback: "opacity",
        stroke: champagne,
        strokeWidth: 0.012,
        opacity: 0.56,
      },
    ],
  },
} as const satisfies Record<Station4NodeId, World4NodeFxConfig>;

export const WORLD4_NODE_FX_ORDER = [
  "planta",
  "bionosificador",
  "esp32",
  "midi",
  "wifi_udp",
  "router",
  "sistema_central",
  "sonido",
] as const satisfies readonly Station4NodeId[];

export function getWorld4NodeFxConfig(nodeId: Station4NodeId) {
  return WORLD4_NODE_FX_CONFIG[nodeId];
}
