import type {
  LoadingInitialSparkleSlot,
  LoadingInitialWaterStream,
} from "./LoadingInitial.types";

export const loadingInitialWaterStreams = [
  {
    id: "waterStreamA",
    className: "loading-initial__water-stream--a",
    delayMs: 0,
    offsetX: "0px",
    offsetY: "0px",
    rotateDeg: -0.6,
    scale: 1,
    cycleDurationMs: 1320,
  },
  {
    id: "waterStreamB",
    className: "loading-initial__water-stream--b",
    delayMs: 180,
    offsetX: "-5px",
    offsetY: "3px",
    rotateDeg: -2.2,
    scale: 0.98,
    cycleDurationMs: 1360,
  },
  {
    id: "waterStreamC",
    className: "loading-initial__water-stream--c",
    delayMs: 340,
    offsetX: "6px",
    offsetY: "5px",
    rotateDeg: 1.8,
    scale: 0.96,
    cycleDurationMs: 1400,
  },
] satisfies LoadingInitialWaterStream[];

export const loadingInitialSparkleSlots = [
  {
    id: "sparkle-lilac-upper-far-left",
    assetIndex: 0,
    className: "loading-initial__sparkle--upper-far-left",
    x: "14%",
    y: "22%",
    delayMs: 600,
    durationMs: 3200,
  },
  {
    id: "sparkle-amber-upper-far-right",
    assetIndex: 1,
    className: "loading-initial__sparkle--upper-far-right",
    x: "84%",
    y: "20%",
    delayMs: 1100,
    durationMs: 3400,
  },
  {
    id: "sparkle-white-upper-center",
    assetIndex: 3,
    className: "loading-initial__sparkle--upper-center",
    x: "52%",
    y: "15%",
    delayMs: 1700,
    durationMs: 3000,
  },
  {
    id: "sparkle-white-middle-left",
    assetIndex: 3,
    className: "loading-initial__sparkle--middle-left",
    x: "20%",
    y: "45%",
    delayMs: 2300,
    durationMs: 2600,
  },
  {
    id: "sparkle-amber-middle-right",
    assetIndex: 1,
    className: "loading-initial__sparkle--middle-right",
    x: "78%",
    y: "42%",
    delayMs: 2900,
    durationMs: 3400,
  },
  {
    id: "sparkle-lilac-near-lia",
    assetIndex: 2,
    className: "loading-initial__sparkle--near-lia",
    x: "68%",
    y: "54%",
    delayMs: 3500,
    durationMs: 3000,
  },
  {
    id: "sparkle-lilac-near-plant",
    assetIndex: 0,
    className: "loading-initial__sparkle--near-plant",
    x: "36%",
    y: "58%",
    delayMs: 4100,
    durationMs: 2800,
  },
  {
    id: "sparkle-amber-lower-left",
    assetIndex: 1,
    className: "loading-initial__sparkle--lower-left",
    x: "15%",
    y: "72%",
    delayMs: 4700,
    durationMs: 3600,
  },
  {
    id: "sparkle-lilac-lower-right",
    assetIndex: 2,
    className: "loading-initial__sparkle--lower-right",
    x: "83%",
    y: "68%",
    delayMs: 5400,
    durationMs: 3200,
  },
  {
    id: "sparkle-white-halo-low",
    assetIndex: 3,
    className: "loading-initial__sparkle--halo-low",
    x: "47%",
    y: "80%",
    delayMs: 6200,
    durationMs: 3000,
  },
] satisfies LoadingInitialSparkleSlot[];
