import type {
  LoadingInitialSparkleSlot,
  LoadingInitialWaterStream,
} from "./LoadingInitial.types";

export const loadingInitialWaterStreams = [
  {
    id: "waterStreamA",
    className: "loading-initial__water-stream--a",
    delayMs: 0,
    offsetX: "0px",
    offsetY: "0px",
    rotateDeg: -0.6,
    scale: 1,
    cycleDurationMs: 1320,
  },
  {
    id: "waterStreamB",
    className: "loading-initial__water-stream--b",
    delayMs: 180,
    offsetX: "-5px",
    offsetY: "3px",
    rotateDeg: -2.2,
    scale: 0.98,
    cycleDurationMs: 1360,
  },
  {
    id: "waterStreamC",
    className: "loading-initial__water-stream--c",
    delayMs: 340,
    offsetX: "6px",
    offsetY: "5px",
    rotateDeg: 1.8,
    scale: 0.96,
    cycleDurationMs: 1400,
  },
] satisfies LoadingInitialWaterStream[];

export const loadingInitialSparkleSlots = [
  {
    id: "sparkle-lilac-upper-far-left",
    assetIndex: 0,
    className: "loading-initial__sparkle--upper-far-left",
    x: "13%",
    y: "18%",
    delayMs: 600,
    durationMs: 3200,
  },
  {
    id: "sparkle-amber-upper-far-right",
    assetIndex: 1,
    className: "loading-initial__sparkle--upper-far-right",
    x: "87%",
    y: "19%",
    delayMs: 1100,
    durationMs: 3400,
  },
  {
    id: "sparkle-white-upper-center",
    assetIndex: 3,
    className: "loading-initial__sparkle--upper-center",
    x: "50%",
    y: "12%",
    delayMs: 1700,
    durationMs: 3000,
  },
  {
    id: "sparkle-white-middle-far-left",
    assetIndex: 3,
    className: "loading-initial__sparkle--middle-far-left",
    x: "16%",
    y: "38%",
    delayMs: 2300,
    durationMs: 2600,
  },
  {
    id: "sparkle-amber-middle-far-right",
    assetIndex: 1,
    className: "loading-initial__sparkle--middle-far-right",
    x: "90%",
    y: "41%",
    delayMs: 2900,
    durationMs: 3400,
  },
  {
    id: "sparkle-lilac-lower-left",
    assetIndex: 2,
    className: "loading-initial__sparkle--lower-left",
    x: "14%",
    y: "63%",
    delayMs: 3500,
    durationMs: 3000,
  },
  {
    id: "sparkle-lilac-lower-right",
    assetIndex: 0,
    className: "loading-initial__sparkle--lower-right",
    x: "88%",
    y: "67%",
    delayMs: 4100,
    durationMs: 2800,
  },
  {
    id: "sparkle-amber-bottom-left",
    assetIndex: 1,
    className: "loading-initial__sparkle--bottom-left",
    x: "24%",
    y: "82%",
    delayMs: 4700,
    durationMs: 3600,
  },
  {
    id: "sparkle-lilac-bottom-right",
    assetIndex: 2,
    className: "loading-initial__sparkle--bottom-right",
    x: "76%",
    y: "82%",
    delayMs: 5400,
    durationMs: 3200,
  },
  {
    id: "sparkle-white-halo-micro-low",
    assetIndex: 3,
    className: "loading-initial__sparkle--halo-micro-low",
    x: "48%",
    y: "88%",
    delayMs: 6200,
    durationMs: 3000,
  },
] satisfies LoadingInitialSparkleSlot[];
