import type { TransitionWorldConfig } from "./transitionWorld.types";
import {
  finalEntryRoute,
  worldFiveEntryRoute,
  worldFourEntryRoute,
  worldOneEntryRoute,
  worldThreeEntryRoute,
  worldTwoEntryRoute,
} from "../../app/routes";
import {
  coverToWorldOneTransitionCopy,
  worldFiveToFinalTransitionCopy,
  worldFourToWorldFiveTransitionCopy,
  worldOneToWorldTwoTransitionCopy,
  worldThreeToWorldFourTransitionCopy,
  worldTwoToWorldThreeTransitionCopy,
} from "../../content/transitionEditorialSlots";

export const TRANSITION_WORLD_VERSION = "T003E7C_TYPOGRAPHY_TOKENS";

export const introToStationOneTransition: TransitionWorldConfig = {
  editorialCopyStatus: coverToWorldOneTransitionCopy.title.status,
  id: "intro-to-station-1",
  fromRoute: "/portada",
  toRoute: worldOneEntryRoute,
  targetPreload: "world1RootInitial",
  title: coverToWorldOneTransitionCopy.title.text,
  titleSlotId: coverToWorldOneTransitionCopy.title.id,
  subtitle: coverToWorldOneTransitionCopy.subtitle.text,
  subtitleSlotId: coverToWorldOneTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transición hacia Mundo I: Raíz",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F7EFD8",
    mist: "#E6DCF7",
    portalCore: "#FFF5C8",
    portalEdge: "#C9B8E8",
    portalGlow: "#E3A33E",
    text: "#4E3F35",
    textSoft: "#7E6248",
    progressTrack: "#D7C9A8",
    progressFill: "#E3A33E",
  },
};

export const worldOneToWorldTwoTransition: TransitionWorldConfig = {
  editorialCopyStatus: worldOneToWorldTwoTransitionCopy.title.status,
  id: "world-1-to-world-2",
  fromRoute: worldOneEntryRoute,
  toRoute: worldTwoEntryRoute,
  targetPreload: "none",
  title: worldOneToWorldTwoTransitionCopy.title.text,
  titleSlotId: worldOneToWorldTwoTransitionCopy.title.id,
  subtitle: worldOneToWorldTwoTransitionCopy.subtitle.text,
  subtitleSlotId: worldOneToWorldTwoTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transicion hacia Mundo II",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F7EFD8",
    mist: "#E6DCF7",
    portalCore: "#FFF5C8",
    portalEdge: "#C9B8E8",
    portalGlow: "#E3A33E",
    text: "#4E3F35",
    textSoft: "#7E6248",
    progressTrack: "#D7C9A8",
    progressFill: "#E3A33E",
  },
};

export const worldTwoToWorldThreeTransition: TransitionWorldConfig = {
  editorialCopyStatus: worldTwoToWorldThreeTransitionCopy.title.status,
  id: "world-2-to-world-3",
  fromRoute: worldTwoEntryRoute,
  toRoute: worldThreeEntryRoute,
  targetPreload: "none",
  title: worldTwoToWorldThreeTransitionCopy.title.text,
  titleSlotId: worldTwoToWorldThreeTransitionCopy.title.id,
  subtitle: worldTwoToWorldThreeTransitionCopy.subtitle.text,
  subtitleSlotId: worldTwoToWorldThreeTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transicion hacia Mundo III",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F7EFD8",
    mist: "#E6DCF7",
    portalCore: "#FFF5C8",
    portalEdge: "#C9B8E8",
    portalGlow: "#E3A33E",
    text: "#4E3F35",
    textSoft: "#7E6248",
    progressTrack: "#D7C9A8",
    progressFill: "#E3A33E",
  },
};

export const worldThreeToWorldFourTransition: TransitionWorldConfig = {
  editorialCopyStatus: worldThreeToWorldFourTransitionCopy.title.status,
  id: "world-3-to-world-4",
  fromRoute: worldThreeEntryRoute,
  toRoute: worldFourEntryRoute,
  targetPreload: "none",
  title: worldThreeToWorldFourTransitionCopy.title.text,
  titleSlotId: worldThreeToWorldFourTransitionCopy.title.id,
  subtitle: worldThreeToWorldFourTransitionCopy.subtitle.text,
  subtitleSlotId: worldThreeToWorldFourTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transicion hacia Mundo IV",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F7EFD8",
    mist: "#E6DCF7",
    portalCore: "#FFF5C8",
    portalEdge: "#C9B8E8",
    portalGlow: "#E3A33E",
    text: "#4E3F35",
    textSoft: "#7E6248",
    progressTrack: "#D7C9A8",
    progressFill: "#E3A33E",
  },
};

export const worldFourToWorldFiveTransition: TransitionWorldConfig = {
  editorialCopyStatus: worldFourToWorldFiveTransitionCopy.title.status,
  id: "world-4-to-world-5",
  fromRoute: worldFourEntryRoute,
  toRoute: worldFiveEntryRoute,
  targetPreload: "none",
  title: worldFourToWorldFiveTransitionCopy.title.text,
  titleSlotId: worldFourToWorldFiveTransitionCopy.title.id,
  subtitle: worldFourToWorldFiveTransitionCopy.subtitle.text,
  subtitleSlotId: worldFourToWorldFiveTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transicion hacia Mundo V",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F7EFD8",
    mist: "#E6DCF7",
    portalCore: "#FFF5C8",
    portalEdge: "#C9B8E8",
    portalGlow: "#E3A33E",
    text: "#4E3F35",
    textSoft: "#7E6248",
    progressTrack: "#D7C9A8",
    progressFill: "#E3A33E",
  },
};

export const worldFiveToFinalTransition: TransitionWorldConfig = {
  editorialCopyStatus: worldFiveToFinalTransitionCopy.title.status,
  id: "world-5-to-final",
  fromRoute: worldFiveEntryRoute,
  toRoute: finalEntryRoute,
  targetPreload: "none",
  title: worldFiveToFinalTransitionCopy.title.text,
  titleSlotId: worldFiveToFinalTransitionCopy.title.id,
  subtitle: worldFiveToFinalTransitionCopy.subtitle.text,
  subtitleSlotId: worldFiveToFinalTransitionCopy.subtitle.id,
  durationMs: 2300,
  reducedMotionDurationMs: 1000,
  portalLabel: "Portal de transicion hacia Pantalla Final",
  portalState: "open",
  portalSymbol: "root",
  palette: {
    background: "#F5F1E7",
    mist: "#DDE8DD",
    portalCore: "#FFF5C8",
    portalEdge: "#9AB8A8",
    portalGlow: "#BF7E30",
    text: "#17241F",
    textSoft: "#58665F",
    progressTrack: "#CDD6CA",
    progressFill: "#2F6F5E",
  },
};

export const transitionWorldConfigs = {
  introToStationOne: introToStationOneTransition,
  worldOneToWorldTwo: worldOneToWorldTwoTransition,
  worldTwoToWorldThree: worldTwoToWorldThreeTransition,
  worldThreeToWorldFour: worldThreeToWorldFourTransition,
  worldFourToWorldFive: worldFourToWorldFiveTransition,
  worldFiveToFinal: worldFiveToFinalTransition,
} as const;
